### ISSUE TITLE
Plugin cannot fetch data

### ISSUE THREAD

**Issue by snsrkn** [anezih/calibre-kitapyurdu#1]
I tried adding book with ISBN and the value before html in the address bar but it didn't work. 

I am trying to add from __Add from ISBN__ menu. 

I can fetch books, but they come from Goodreads, Amazon or Google, not Kitapyurdu. When I try to add with __kitapyurdu:123456__ I always get "failed to download metadata..." error. 

__Calibre version:__ 7.2.0

**Comment by anezih** [comment]
> I tried adding book with ISBN and the value before html in the address bar but it didn't work.
> 
> I am trying to add from **Add from ISBN** menu.
> 
> I can fetch books, but they come from Goodreads, Amazon or Google, not Kitapyurdu. When I try to add with **kitapyurdu:123456** I always get "failed to download metadata..." error.
> 
> **Calibre version:** 7.2.0

Ekteki sürümü test edebilir misiniz? Çalışıyorsa güncelleme geçeceğim.
Yüklü eklentiyi sildikten sonra Tercihler > Eklentiler > "Eklentiyi dosyadan yükle" ile ekteki dosyayı yükleyin.
[kitapyurdu.zip](https://github.com/anezih/calibre-kitapyurdu/files/13696165/kitapyurdu.zip)

**Comment by snsrkn** [comment]
Çalışıyor, çok teşekkür ederim. Elinize sağlık.

**Comment by anezih** [comment]
Güncelleme [eklenti dizinine](https://plugins.calibre-ebook.com) de yansımış, şu an için bir sorun yok gözüküyor.
